In [1]:
# Dataframes - regular, dsy, pastYear

import pandas as pd

df = pd.read_csv('merged_df2.csv')


df['UID'] = df['UID'].astype(str)


regular_df = df[df['UID'].str.startswith('2019')]
dsy_df = df[df['UID'].str.startswith('2020')]
prev_df = df[df['UID'].str.startswith('2018')]

# regular_df
prev_df

,UID,Name,SGPA_1,Results_1,SGPA_2,Results_2,SGPA_3,Results_3,SGPA_4,Results_4,SGPA_5,Results_5,SGPA_6,Results_6,SGPA_7,Results_7,SGPA_8,Results_8
0,2018120014,CONTRACTOR VARUN MANOJ DARSHANA,NaN,NaN,NaN,NaN,8.857143,P,6.578947,P,6.48,P,5.45,P,6.25,P,10.0000,P
1,2018120016,DATTA SOHEL,NaN,NaN,NaN,NaN,7.620000,P,6.421053,P,6.38,P,5.15,P,6.00,P,9.8750,P
2,2018120018,DHODI NIRAJ SURESH SUNITA,NaN,NaN,NaN,NaN,7.952381,P,7.530000,P,7.52,P,7.85,P,8.13,P,10.0000,P
3,2018120047,PATEL SHIVAM DHANSUKH RITA,NaN,NaN,NaN,NaN,8.050000,P,7.210000,P,7.14,P,7.20,P,7.56,P,10.0000,P
4,2018120059,TRUPTI GOPINATH JAYALAKSHMI,NaN,NaN,NaN,NaN,8.710000,P,7.421053,P,7.24,P,NaN,NaN,6.44,P,7.7500,P
5,2018120062,WADIKAR YUGANDHARA DATTATRAY SUNITA,NaN,NaN,NaN,NaN,8.050000,P,8.000000,P,7.81,P,7.95,P,8.50,P,9.9375,P

In [2]:
## First Year - regular students 


FEcount_F = 0
FEcount_P = 0

FEbacklog_list = []
FEregular_list = []


for index, row in regular_df.iterrows():
    
    result1 = row['Results_1']
    result2 = row['Results_2']
    
   
    if (result1 == 'F' or result2 == 'F'):
        FEcount_F += 1
        FEbacklog_list.append(row['UID'])
    elif (result1 == 'P' and result2 == 'P'):
        FEcount_P += 1
        FEregular_list.append(row['UID'])

# Display the counts
print("Number of F (FE):", FEcount_F)
print("Number of P (FE):", FEcount_P)

# Display the backlog and regular lists
print("Backlog List (FE):", FEbacklog_list)
print("Regular List (FE):", FEregular_list)

Number of F (FE): 8
Number of P (FE): 60
Backlog List (FE): ['2019120008', '2019120021', '2019120026', '2019120036', '2019120049', '2019120051', '2019120066', '2019120067']
Regular List (FE): ['2019120001', '2019120002', '2019120003', '2019120004', '2019120005', '2019120006', '2019120007', '2019120009', '2019120010', '2019120011', '2019120012', '2019120013', '2019120014', '2019120015', '2019120016', '2019120017', '2019120018', '2019120019', '2019120020', '2019120022', '2019120023', '2019120024', '2019120025', '2019120027', '2019120028', '2019120029', '2019120030', '2019120031', '2019120032', '2019120033', '2019120034', '2019120035', '2019120037', '2019120038', '2019120039', '2019120040', '2019120041', '2019120042', '2019120043', '2019120044', '2019120045', '2019120046', '2019120047', '2019120048', '2019120050', '2019120052', '2019120053', '2019120054', '2019120055', '2019120056', '2019120057', '2019120058', '2019120059', '2019120060', '2019120061', '2019120062', '2019120063', '2019120064', '2019120065', '2019120068']

In [3]:
## Second Year - regular students

SEreg_count_F = 0
SEreg_count_P = 0
SEreg_count_N = 0


SEbacklog_list = []
SEregular_list = []
SEdsy_empty_list = []



for index, row in regular_df.iterrows():
    
    result3 = row['Results_3']
    result4 = row['Results_4']
    
   
    if (result3 == 'F' or result4 == 'F'):
        SEreg_count_F += 1
        SEbacklog_list.append(row['UID'])
    elif (result3 == 'P' and result4 == 'P'):
        SEreg_count_P += 1
        SEregular_list.append(row['UID'])
    else:
        SEreg_count_N +=1
        SEdsy_empty_list.append(row['UID'])    

# Display the counts
print("Number of F (SE-reg):", SEreg_count_F)
print("Number of P (SE-reg):", SEreg_count_P)
print("Number of NaN (SE-reg):", SEreg_count_N)

# Display the backlog and regular lists
print("Backlog List (SE-reg):", SEbacklog_list)
print("Regular List (SE-reg):", SEregular_list)
print("Empty List (SE-reg):", SEdsy_empty_list)

Number of F (SE-reg): 0
Number of P (SE-reg): 65
Number of NaN (SE-reg): 3
Backlog List (SE-reg): []
Regular List (SE-reg): ['2019120001', '2019120002', '2019120003', '2019120004', '2019120005', '2019120006', '2019120007', '2019120008', '2019120009', '2019120010', '2019120011', '2019120012', '2019120013', '2019120014', '2019120015', '2019120016', '2019120017', '2019120018', '2019120019', '2019120020', '2019120021', '2019120022', '2019120023', '2019120024', '2019120025', '2019120027', '2019120028', '2019120029', '2019120030', '2019120031', '2019120032', '2019120033', '2019120034', '2019120035', '2019120037', '2019120038', '2019120039', '2019120040', '2019120041', '2019120042', '2019120043', '2019120044', '2019120045', '2019120046', '2019120047', '2019120048', '2019120049', '2019120050', '2019120051', '2019120052', '2019120053', '2019120054', '2019120055', '2019120056', '2019120057', '2019120058', '2019120059', '2019120060', '2019120061', '2019120062', '2019120063', '2019120064', '2019120065', '2019120066', '2019120068']
Empty List (SE-reg): ['2019120026', '2019120036', '2019120067']

In [4]:
## Third Year - regular students


TEregcount_F = 0
TEregcount_P = 0
TEregcount_N = 0


TEbacklog_list = []
TEregular_list = []
TEempty_list = []

for index, row in regular_df.iterrows():
    
    result5 = row['Results_5']
    result6 = row['Results_6']
    
   
    if (result5 == 'F' or result6 == 'F'):
        TEregcount_F += 1
        TEbacklog_list.append(row['UID'])
    elif (result5 == 'P' and result6 == 'P') or (result5 == 'P' and pd.isnull(result6)):
        TEregcount_P += 1
        TEregular_list.append(row['UID'])
    else:
        TEregcount_N +=1
        TEempty_list.append(row['UID'])    

# Display the counts
print("Number of F (TE-reg):", TEregcount_F)
print("Number of P (TE-reg):", TEregcount_P)
print("Number of NaN (TE-reg):", TEregcount_N)

# Display the backlog and regular lists
print("Backlog List (TE-reg):", TEbacklog_list)
print("Regular List (TE-reg):", TEregular_list)
print("Empty List (TE-reg):", TEempty_list)

Number of F (TE-reg): 0
Number of P (TE-reg): 65
Number of NaN (TE-reg): 3
Backlog List (TE-reg): []
Regular List (TE-reg): ['2019120001', '2019120002', '2019120003', '2019120004', '2019120005', '2019120006', '2019120007', '2019120008', '2019120009', '2019120010', '2019120011', '2019120012', '2019120013', '2019120014', '2019120015', '2019120016', '2019120017', '2019120018', '2019120019', '2019120020', '2019120021', '2019120022', '2019120023', '2019120024', '2019120025', '2019120027', '2019120028', '2019120029', '2019120030', '2019120031', '2019120032', '2019120033', '2019120034', '2019120035', '2019120037', '2019120038', '2019120039', '2019120040', '2019120041', '2019120042', '2019120043', '2019120044', '2019120045', '2019120046', '2019120047', '2019120048', '2019120049', '2019120050', '2019120051', '2019120052', '2019120053', '2019120054', '2019120055', '2019120056', '2019120057', '2019120058', '2019120059', '2019120060', '2019120061', '2019120062', '2019120063', '2019120064', '2019120065', '2019120066', '2019120068']
Empty List (TE-reg): ['2019120026', '2019120036', '2019120067']

In [10]:
## Fourth Year - regular students

BEregcount_F = 0
BEregcount_P = 0
BEregcount_N = 0


BEbacklog_list = []
BEregular_list = []
BEempty_list = []

for index, row in regular_df.iterrows():
    
    result7 = row['Results_7']
    result8 = row['Results_8']
    
   
    if (result7 == 'F' or result8 == 'F'):
        BEregcount_F += 1
        BEbacklog_list.append(row['UID'])
    elif (result7 == 'P' and result8 == 'P') or (result7 == 'P' and pd.isnull(result8)):
        BEregcount_P += 1
        BEregular_list.append(row['UID'])
    else:
        BEregcount_N +=1
        BEempty_list.append(row['UID'])    

# Display the counts
print("Number of F (BE-reg):", BEregcount_F)
print("Number of P (BE-reg):", BEregcount_P)
print("Number of NaN (BE-reg):", BEregcount_N)

# Display the backlog and regular lists
print("Backlog List (BE-reg):", BEbacklog_list)
print("Regular List (BE-reg):", BEregular_list)
print("Empty List (BE-reg):", BEempty_list)

Number of F (BE-reg): 0
Number of P (BE-reg): 65
Number of NaN (BE-reg): 3
Backlog List (BE-reg): []
Regular List (BE-reg): ['2019120001', '2019120002', '2019120003', '2019120004', '2019120005', '2019120006', '2019120007', '2019120008', '2019120009', '2019120010', '2019120011', '2019120012', '2019120013', '2019120014', '2019120015', '2019120016', '2019120017', '2019120018', '2019120019', '2019120020', '2019120021', '2019120022', '2019120023', '2019120024', '2019120025', '2019120027', '2019120028', '2019120029', '2019120030', '2019120031', '2019120032', '2019120033', '2019120034', '2019120035', '2019120037', '2019120038', '2019120039', '2019120040', '2019120041', '2019120042', '2019120043', '2019120044', '2019120045', '2019120046', '2019120047', '2019120048', '2019120049', '2019120050', '2019120051', '2019120052', '2019120053', '2019120054', '2019120055', '2019120056', '2019120057', '2019120058', '2019120059', '2019120060', '2019120061', '2019120062', '2019120063', '2019120064', '2019120065', '2019120066', '2019120068']
Empty List (BE-reg): ['2019120026', '2019120036', '2019120067']

In [5]:
## Second Year - dsy students

SEdsy_count_F = 0
SEdsy_count_P = 0
SEdsy_count_N = 0


SEdsy_backlog_list = []
SEdsy_regular_list = []
SEdsy_empty_list = []



for index, row in dsy_df.iterrows():
    
    result3 = row['Results_3']
    result4 = row['Results_4']
    
   
    if (result3 == 'F' or result4 == 'F'):
        SEdsy_count_F += 1
        SEdsy_backlog_list.append(row['UID'])
    elif (result3 == 'P' and result4 == 'P'):
        SEdsy_count_P += 1
        SEdsy_regular_list.append(row['UID'])
    else:
        SEdsy_count_N +=1
        SEdsy_empty_list.append(row['UID'])    

# Display the counts
print("Number of F (SE-dsy):", SEdsy_count_F)
print("Number of P (SE-dsy):", SEdsy_count_P)
print("Number of NaN (SE-dsy):", SEdsy_count_N)

# Display the backlog and regular lists
print("Backlog List (SE-dsy):", SEdsy_backlog_list)
print("Regular List (SE-dsy):", SEdsy_regular_list)
print("Empty List (SE-dsy):", SEdsy_empty_list)

Number of F (SE-dsy): 2
Number of P (SE-dsy): 10
Number of NaN (SE-dsy): 0
Backlog List (SE-dsy): ['2020201065', '2020201071']
Regular List (SE-dsy): ['2020201063', '2020201064', '2020201066', '2020201067', '2020201068', '2020201069', '2020201070', '2020201072', '2020201073', '2020201074']
Empty List (SE-dsy): []

In [6]:
## Third Year - dsy students


TEdsy_count_F = 0
TEdsy_count_P = 0
TEdsy_count_N = 0


TEdsy_backlog_list = []
TEdsy_regular_list = []
TEdsy_empty_list = []

for index, row in dsy_df.iterrows():
    
    result5 = row['Results_5']
    result6 = row['Results_6']
    
   
    if (result5 == 'F' or result6 == 'F'):
        TEdsy_count_F += 1
        TEdsy_backlog_list.append(row['UID'])
    elif (result5 == 'P' and result6 == 'P') or (result5 == 'P' and pd.isnull(result6)):
        TEdsy_count_P += 1
        TEdsy_regular_list.append(row['UID'])
    else:
        TEdsy_count_N +=1
        TEdsy_empty_list.append(row['UID'])    

# Display the counts
print("Number of F (TE-dsy):", TEdsy_count_F)
print("Number of P (TE-dsy):", TEdsy_count_P)
print("Number of NaN (TE-dsy):", TEdsy_count_N)

# Display the backlog and regular lists
print("Backlog List (TE-dsy):", TEdsy_backlog_list)
print("Regular List (TE-dsy):", TEdsy_regular_list)
print("Empty List (TE-dsy):", TEdsy_empty_list)

Number of F (TE-dsy): 0
Number of P (TE-dsy): 10
Number of NaN (TE-dsy): 2
Backlog List (TE-dsy): []
Regular List (TE-dsy): ['2020201063', '2020201064', '2020201066', '2020201067', '2020201068', '2020201069', '2020201070', '2020201072', '2020201073', '2020201074']
Empty List (TE-dsy): ['2020201065', '2020201071']

In [11]:
## Fourth Year - dsy students

BEdsy_count_F = 0
BEdsy_count_P = 0
BEdsy_count_N = 0


BEdsy_backlog_list = []
BEdsy_regular_list = []
BEdsy_empty_list = []

for index, row in dsy_df.iterrows():
    
    result7 = row['Results_7']
    result8 = row['Results_8']
    
   
    if (result7 == 'F' or result8 == 'F'):
        BEdsy_count_F += 1
        BEdsy_backlog_list.append(row['UID'])
    elif (result7 == 'P' and result8 == 'P') or (result7 == 'P' and pd.isnull(result8)):
        BEdsy_count_P += 1
        BEdsy_regular_list.append(row['UID'])
    else:
        BEdsy_count_N +=1
        BEdsy_empty_list.append(row['UID'])    

# Display the counts
print("Number of F (BE-dsy):", BEdsy_count_F)
print("Number of P (BE-dsy):", BEdsy_count_P)
print("Number of NaN (BE-dsy):", BEdsy_count_N)

# Display the backlog and regular lists
print("Backlog List (BE-dsy):", BEdsy_backlog_list)
print("Regular List (BE-dsy):", BEdsy_regular_list)
print("Empty List (BE-dsy):", BEdsy_empty_list)

Number of F (BE-dsy): 1
Number of P (BE-dsy): 9
Number of NaN (BE-dsy): 2
Backlog List (BE-dsy): ['2020201066']
Regular List (BE-dsy): ['2020201063', '2020201064', '2020201067', '2020201068', '2020201069', '2020201070', '2020201072', '2020201073', '2020201074']
Empty List (BE-dsy): ['2020201065', '2020201071']

In [7]:
## Second Year - prev years 


SEprev_count_F = 0
SEprev_count_P = 0
SEprev_count_N = 0


SEprev_backlog_list = []
SEprev_regular_list = []
SEprev_empty_list = []



for index, row in prev_df.iterrows():
    
    result3 = row['Results_3']
    result4 = row['Results_4']
    
   
    if (result3 == 'F' or result4 == 'F'):
        SEprev_count_F += 1
        SEprev_backlog_list.append(row['UID'])
    elif (result3 == 'P' and result4 == 'P'):
        SEprev_count_P += 1
        SEprev_regular_list.append(row['UID'])
    else:
        SEprev_count_N +=1
        SEprev_empty_list.append(row['UID'])    

# Display the counts
print("Number of F (SE-prev):", SEprev_count_F)
print("Number of P (SE-prev):", SEprev_count_P)
print("Number of NaN (SE-prev):", SEprev_count_N)

# Display the backlog and regular lists
print("Backlog List (SE-prev):", SEprev_backlog_list)
print("Regular List (SE-prev):", SEprev_regular_list)
print("Empty List (SE-prev):", SEprev_empty_list)

Number of F (SE-prev): 0
Number of P (SE-prev): 6
Number of NaN (SE-prev): 0
Backlog List (SE-prev): []
Regular List (SE-prev): ['2018120014', '2018120016', '2018120018', '2018120047', '2018120059', '2018120062']
Empty List (SE-prev): []

In [8]:
## Third Year - prev students


TEprev_count_F = 0
TEprev_count_P = 0
TEprev_count_N = 0


TEprev_backlog_list = []
TEprev_regular_list = []
TEprev_empty_list = []

for index, row in prev_df.iterrows():
    
    result5 = row['Results_5']
    result6 = row['Results_6']
    
   
    if (result5 == 'F' or result6 == 'F'):
        TEprev_count_F += 1
        TEprev_backlog_list.append(row['UID'])
    elif (result5 == 'P' and result6 == 'P') or (result5 == 'P' and pd.isnull(result6)):
        TEprev_count_P += 1
        TEprev_regular_list.append(row['UID'])
    else:
        TEprev_count_N +=1
        TEprev_empty_list.append(row['UID'])    

# Display the counts
print("Number of F (TE-prev):", TEprev_count_F)
print("Number of P (TE-prev):", TEprev_count_P)
print("Number of NaN (TE-prev):", TEprev_count_N)

# Display the backlog and regular lists
print("Backlog List (TE-prev):", TEprev_backlog_list)
print("Regular List (TE-prev):", TEprev_regular_list)
print("Empty List (TE-prev):", TEprev_empty_list)

Number of F (TE-prev): 0
Number of P (TE-prev): 6
Number of NaN (TE-prev): 0
Backlog List (TE-prev): []
Regular List (TE-prev): ['2018120014', '2018120016', '2018120018', '2018120047', '2018120059', '2018120062']
Empty List (TE-prev): []

In [12]:
## Fourth Year - prev students


BEprev_count_F = 0
BEprev_count_P = 0
BEprev_count_N = 0


BEprev_backlog_list = []
BEprev_regular_list = []
BEprev_empty_list = []

for index, row in prev_df.iterrows():
    
    result7 = row['Results_7']
    result8 = row['Results_8']
    
   
    if (result7 == 'F' or result8 == 'F'):
        BEprev_count_F += 1
        BEprev_backlog_list.append(row['UID'])
    elif (result7 == 'P' and result8 == 'P') or (result7 == 'P' and pd.isnull(result8)):
        BEprev_count_P += 1
        BEprev_regular_list.append(row['UID'])
    else:
        BEprev_count_N +=1
        BEprev_empty_list.append(row['UID'])    

# Display the counts
print("Number of F (BE-prev):", BEprev_count_F)
print("Number of P (BE-prev):", BEprev_count_P)
print("Number of NaN (BE-prev):", BEprev_count_N)

# Display the backlog and regular lists
print("Backlog List (BE-prev):", BEprev_backlog_list)
print("Regular List (BE-prev):", BEprev_regular_list)
print("Empty List (BE-prev):", BEprev_empty_list)

Number of F (BE-prev): 0
Number of P (BE-prev): 6
Number of NaN (BE-prev): 0
Backlog List (BE-prev): []
Regular List (BE-prev): ['2018120014', '2018120016', '2018120018', '2018120047', '2018120059', '2018120062']
Empty List (BE-prev): []